import React from "react";
import "./Career.css";

const partners = [
  { name: "Google", icon: "G" },
  { name: "Microsoft", icon: "▦" },
  { name: "Oracle", icon: "▰" },
  { name: "LinkedIn", icon: "in" }
];

const Career = () => {
  return (
    <section className="career-section">

      <div className="career-cards">

        <div className="roadmap-card">

          <div className="roadmap-content">
            <p className="small-title">New AI-Powered ✨</p>

            <h2>
              <span>AI Roadmap</span> Generator
            </h2>

            <p className="roadmap-description">
              Unlock your potential with a personalized
              learning roadmap generated by AI.
            </p>

            <div className="roadmap-points">
              <p>✓ Choose your career goal</p>
              <p>✓ Tell us your current level</p>
              <p>✓ Get a step-by-step learning plan</p>
              <p>✓ Download your roadmap</p>
            </div>

            <div className="roadmap-brand">
              <strong>All with</strong>
              <br />
              <span>◈ STEPS</span>
            </div>
          </div>

          <div className="roadmap-form">
            <label>Select your Goal</label>

            <select>
              <option>Web Development</option>
              <option>App Development</option>
              <option>UI/UX Design</option>
              <option>Data Science</option>
            </select>

            <label>Your current level</label>

            <select>
              <option>Beginner</option>
              <option>Intermediate</option>
              <option>Advanced</option>
            </select>

            <button>Generate Roadmap</button>
          </div>

        </div>


        <div className="internship-card">

          <div className="internship-content">

            <p className="career-label">Kickstart Your Career</p>

            <h2>Internship Opportunities</h2>

            <p className="internship-description">
              Join our industry-focused internship
              programs and gain real-world experience.
            </p>

            <div className="internship-features">

              <div>
                <span>♟</span>
                <p>Industry<br />Expert</p>
              </div>

              <div>
                <span>▣</span>
                <p>Certificates &<br />LOR</p>
              </div>

              <div>
                <span>▤</span>
                <p>Real World<br />Projects</p>
              </div>

              <div>
                <span>◉</span>
                <p>Placement<br />Assistance</p>
              </div>

            </div>

            <button className="explore-btn">
              Explore Internship →
            </button>

          </div>

          <div className="internship-image">
            <img
              src="https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=700&q=80"
              alt="Students working together"
            />
          </div>

        </div>

      </div>


      <h2 className="partners-title">
        Our Trusted Partners & Clients
      </h2>

      <div className="partners">

        {partners.map((partner, index) => (
          <div className="partner-card" key={index}>
            <span className={`partner-icon partner-${index}`}>
              {partner.icon}
            </span>

            <span>{partner.name}</span>
          </div>
        ))}

      </div>

    </section>
  );
};

export default Career;